### ISSUE TITLE
Pin browser

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-browser#323]
Add a pin to the left hand side of the browser title bar. Clicking the pin will lock the position and size of the browser as well as disabling the closing X.

Enabling pin will:
1. Lock width and height of the browser
2. Lock position of the browser
3. Remove X from top right of browser (or grey out)
4. Disable draggability on left-hand preview bar icon
5. Disable closing (x) from left-hand preview bar icon

Bonus:
Pin and unpin from context menu of left-hand preview bar icon.

Bonus 2:
'Pin all' and 'unpin all' from context menu of board tab (top bar).

**Comment by danielfebrero** [comment]
@dcallus great one. my first associate at my first browser requested the same. it has been implemented successfully and became essential.
