### ISSUE TITLE
Full screen not working MacOs 30.4

### ISSUE THREAD

**Issue by Nuklusone** [BonBon-exchange/bonbon-browser#339]
## Expected Behavior

Video should open in full screen

## Current Behavior

Full screen doesn't work. You can't enter full screen. When you do enter it you can't exit it. 
## Steps to Reproduce

1.Open a video on full screen

2.Try to exit full screen

**Comment by danielfebrero** [comment]
Weird, thank you for this. The only thing I see is that we updated electron version, but I will review. 
@dcallus can you reproduce this?

**Comment by dcallus** [comment]
@Nuklusone could you let us know what site you were watching to view fullscreen video and how you tried to minimise the screen?

I've just tried youtube and both the 'escape' key and pressing the minimise video button worked.

**Comment by Nuklusone** [comment]
@dcallus it was on 9anime.me (and it's subsites) but I was able to reproduce it on youtube and other sites.
