### ISSUE TITLE
App Screen Width Calculation Bug || Minor Overlay Bug 

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-browser#385]
This is either a screen width calculation bug in Browser.tsx or a minor CSS bug for the .Board__edge-snap-maximized class (or the JS that modifies it in Browser.tsx).

I've tried everything I can with the CSS, but I honestly think there is an issue with the app width calculation. I am using VW which should always find the width of the current viewport, yet it is not consistent.
## Expected Behavior
Expected behaviour should be like this right edge snap. As you can see, even though I resize the window's height, the height (based on VH) of the overlay remains pretty relative to the app. i.e. the overlay still fits in at about 98% of screen height.
![clip1_side_good](https://user-images.githubusercontent.com/80394290/183971320-3822d72c-da9b-4d60-8f75-435fb5fc5325.gif)

## Current Behavior
As you can see, with the maximise overlay, it does not behave like the side snap overlay. The height works as before, but the width does not. Even though the code is almost identical. The VW does not seem to track correctly, but VH does. The overlay should be approx. 98% of screen width, no matter how wide the app is, but it seems to go completely off the screen to the right when the width of the app is decreased.

If this is just a css bug, it's not really a high priority, but I have a suspicion that the width calculation is incorrect, but I don't know how to verify this.
![clip1_max_not-good](https://user-images.githubusercontent.com/80394290/183972486-587e706b-a1e7-4d15-997b-f30dbdfe5e11.gif)

## Steps to Reproduce

1. Drag a window to the top (maximise zone) and look at the overlay (full screen or similar).

2. Overlay takes up ~98% of the screen width.

3. Resize the app window to 50% of what it was before.

4. Repeat step 1 and notice that the width of the overlay now exceeds that of the viewport.

N/A

**Comment by danielfebrero** [comment]
@dcallus wow i needed like 2 minutes to see where was the issue. good one
