### ISSUE TITLE
App vertical resize breaks functionality.

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-browser#386]
## Expected Behavior
Vertical resizing of the app should work as expected.

## Current Behavior

Resizing the app vertically (to decrease the height) can have strange side-effects if it is done rapidly or to the extreme. An increasing amount of white space appears on the bottom of the app (possibly related to #350) @danielfebrero please verify if this bug happens on windows also. 

Also possibly related to #385 if indeed app dimension tracking is off. Although curiously here only height seems to be effected, not width. 

As you can see. Horizontal resizing has no issue. Vertical resizing does. Not only does it create a lot of white space. It also screws up the cursor's perception of where things are in the app. You will see that I can no longer drag from the title bar and the grab cursor is now much further down.
![clip2_resize_weird](https://user-images.githubusercontent.com/80394290/183975703-33ff8b4b-1291-481b-8235-9c082efb99d2.gif)

## Steps to Reproduce
1. Drag window from bottom resize handle up and down in a crazed manner.
2. Watch the white space increase on the bottom
3. Note that the mouse pointer is not understanding where objects are located.

**Comment by danielfebrero** [comment]
I tested on Windows and cannot reproduce!

![Recording 2022-08-11 at 23 05 23](https://user-images.githubusercontent.com/20900798/184242062-dd213155-4a5e-42b4-9365-e2f1807b9b4b.gif)
