### ISSUE TITLE
Toggle minimap always on.

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-browser#400]
I like the minimap feature quite a lot for scrolling up and down and would like to see it permanently on the right, like it was for a short time. It could be 'hidden when not in use' by default and 'permanent' would be an option to be chosen in the settings.

**Comment by danielfebrero** [comment]
@dcallus how would you deal with webviews in "fit-screen" format ? would you hide some of the webview heind the minimap or reduce length of the webview?
