### ISSUE TITLE
Full screen problem MacOs 0.36.0

### ISSUE THREAD

**Issue by Nuklusone** [BonBon-exchange/bonbon-browser#447]
## Expected Behavior

Opening a video on full screen looks like this.

<img width="1440" alt="Screenshot 2022-08-23 at 21 26 37" src="https://user-images.githubusercontent.com/110396886/186248930-8bec5ab5-a1b6-4d49-9354-0c9642e847f6.png">

Exiting a video on full screen result in this.

<img width="1435" alt="Screenshot 2022-08-23 at 21 26 30" src="https://user-images.githubusercontent.com/110396886/186249041-eaae6731-85ec-42bf-85b1-ddd2544a0d11.png">

## Current Behavior

A video in full screen looks like this

<img width="1440" alt="Screenshot 2022-08-23 at 21 29 37" src="https://user-images.githubusercontent.com/110396886/186249423-6f39abc6-4a1f-4874-a2d5-be422afc3df5.png">

Upon exiting full screen the video will look like this

<img width="1440" alt="Screenshot 2022-08-23 at 21 29 44" src="https://user-images.githubusercontent.com/110396886/186249704-4a527f0d-b356-4f0a-a2bd-cb1fb5e802ec.png">

Note: Quitting the application solves the issue. It's not only happening on youtube, but on every site where you can full screen a video.

## Steps to Reproduce

1. Go to a website where the video can be put into full screen mode.

2. Put the video in full screen

3. Exit full screen

**Comment by danielfebrero** [comment]
Hi @Nuklusone thank you for the report. I'm not sure what I should see here. Is the issue that the top bar tabulation is still visible in full screen, or is it about black bands at the top and bottom of the screen?
